site_name: SDLC Documentation
theme: 'readthedocs'
markdown_extensions: ['markdown.extensions.include', 'extra']
pages:
  - ['index.md', 'Home']
  - ['bns/index.md', 'BNS Library', 'Index']
  - ['bns/sample-bns.md', 'BNS Library', 'A Sample BNS Document']